FROM node:14.17.0-alpine

LABEL maintainer="Thiago Rodrigues <ti.thiago.rodrigues@outlook.com>"

# Create app directory
WORKDIR /var/www/finances

# Install app dependencies - For NPM use: `COPY package.json package-lock.lock ./`
COPY package.json yarn.lock ./ 
# For NPM use: `RUN npm ci`
RUN yarn --pure-lockfile

# Copy important files - Add ormconfig.ts here if using Typeorm
COPY .eslintrc.js nest-cli.json tsconfig.json tsconfig.build.json ormconfig.js ./

# Copy env
COPY .env.docker /var/www/finances/.env

# Add storage folder to the container (If you want to add other folder contents to the container)
# ADD storage /var/www/finances/storage

# Entrypoint command - Replace `"yarn"` with `"npm", "run"` if you are using NPM as your package manager.
# You can update this to run other NodeJS apps
CMD "ls -a"
CMD [ "yarn", "start:dev", "--preserveWatchOutput" ]