name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: Install Dependecies
        working-directory: ./server
        run: yarn        
    
      - name: Build
        working-directory: ./server
        run: yarn build
        
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /live
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: "${{ secrets.SSH_KEY }}"

      
#       - name: copy file via ssh key
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USER }}
#           key: ${{ secrets.SSH_KEY }}
#           port: ${{ secrets.SSH_PORT }}
#           source: "., !node_modules"
#           target: "~/live"
